# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from th2 import connectivity_pb2 as th2_dot_connectivity__pb2


class ConnectivityStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getQueueInfo = channel.unary_unary(
                '/th2.Connectivity/getQueueInfo',
                request_serializer=th2_dot_connectivity__pb2.QueueRequest.SerializeToString,
                response_deserializer=th2_dot_connectivity__pb2.QueueInfo.FromString,
                )


class ConnectivityServicer(object):
    """Missing associated documentation comment in .proto file"""

    def getQueueInfo(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConnectivityServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getQueueInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.getQueueInfo,
                    request_deserializer=th2_dot_connectivity__pb2.QueueRequest.FromString,
                    response_serializer=th2_dot_connectivity__pb2.QueueInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'th2.Connectivity', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Connectivity(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def getQueueInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/th2.Connectivity/getQueueInfo',
            th2_dot_connectivity__pb2.QueueRequest.SerializeToString,
            th2_dot_connectivity__pb2.QueueInfo.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
